config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers =>{
                 :registrations => 'registrations',
                 :omniauth_callbacks => "users/omniauth_callbacks"
                   }
  
  resources :users
  
  resources :twixts do
    resources :comments, :only => [:create, :destroy]
  end

  resources :users do
    member do
      get :follow, :unfollow
    end
  end

  get 'timeline', to: 'users#timeline', as: 'timeline'
  get 'search', to: 'users#search', as: 'search'
  
  root 'twixts#index'
 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :twixt
  belongs_to :user
  validates :body, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/twixt.rb
class Twixt < ActiveRecord::Base
  belongs_to :user
  has_many :comments
    accepts_nested_attributes_for :comments
  validates :user_id, presence: true
  validates :content, length: { maximum: 140 }

  def self.populate!
    30.times do
      t = Twixt.new
      t.user_id = Random.rand(1..User.count)
      t.content = Faker::Hacker.say_something_smart
      t.save
    end
  end

  def self.search(word)
    where (["LOWER(content) LIKE ?", "%#{word.downcase}%"])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  
  has_many :twixts, dependent: :destroy
  has_many :comments

  acts_as_followable
  acts_as_follower

  def display_name
    name.blank? ? email : name
  end

  def self.populate!
    30.times do
      u = User.new
      u.name = Faker::Name.name
      u.email = Faker::Internet.email(u.name)
      u.password = Faker::Internet.password(8)
      u.password_confirmation = u.password
      u.avatar = Faker::Avatar.image
      u.save
    end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first
    unless user
        user = User.create(name: data["name"],
           email: data["email"],
           password: Devise.friendly_token[0,20]
        )
    end
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  

def create
  @twixt = Twixt.find(params[:twixt_id])
  @comment = @twixt.comments.create(comment_params)
 
  if @comment.save
    flash[:success] = 'Your comment was successfully added!'
    redirect_to root_url
  else
    render 'new'
  end
end

def destroy

  @comment = Comment.find(params[:id])
  @comment.destroy
    
    redirect_to :back, :notice => "Removed Comment."
end
 
private
 
  def comment_params
    params.require(:comment).permit(:user_id, :body)
  end
  
end

app/controllers/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  def search(word)
    searched_twixts = []
    twixts = Twixt.order(created_at: :desc)
    twixs.each do |twixt|
      if twixt.include? word
        searched_twixts << twixt
      end
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise :: OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create, :update]
  protected

  def configure_permitted_parameters
    attributes = [:name, :email, :avatar, :password, :password_confirmation]
    
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(*attributes) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(*(attributes + [:current_password])) }
  end
end

app/controllers/twixts_controller.rb
class TwixtsController < ApplicationController
  before_action :set_twixt, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    @twixts = Twixt.order(created_at: :desc).page(params[:page])
  end

  def show
    @twixts = Twixt.all
    @comment = Comment.new
  end

  def new
    @twixt = current_user.twixts.build
  end

  def edit
  end

  def create
    @twixt = current_user.twixts.new(twixt_params)

    if @twixt.save
      redirect_to twixts_path, notice: 'Twixt was successfully created.'
    else
      render :new
    end
  end

  def update
    if @twixt.update(twixt_params)
      redirect_to @twixt, notice: 'Twixt was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @twixt.destroy
    redirect_to twixts_url, notice: 'Twixt was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_twixt
    @twixt = Twixt.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def twixt_params
    params.require(:twixt).permit(:content)
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
  
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :following, :followers]
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @twixts = Twixt.where(user_id: @user.id).order(created_at: :desc)
  end

  def create
    @user = User.new(params[:user])
 
    if @user.save
      redirect_to @user, notice: "Thank you for signing up for Twixter!"
    else
    render 'new'
    end
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    redirect_to @user
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.stop_following(@user)
    redirect_to @user
  end

  def timeline
    follower_ids = current_user.all_following.map(&:id)
    all_ids = follower_ids << current_user.id
    @twixts = Twixt.where(user_id: all_ids).order(created_at: :DESC).page(params[:page])
  end

  def search
    @twixts = Twixt.search(params[:word])
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email_address, :avatar, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/twixts_helper.rb
module TwixtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Join the discussion</h1>
    <p>Click the button below to start a new thread:</p>
    <p>
      <%= link_to 'Add new topic', new_comment_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>
 
<%= render @comments %>

app/views/comments/new.html.erb
<h1>New comment</h1>
 
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <title>Twixter</title>
      <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
  </head>

<body>
  <div class="masthead">
    <div class="container">
     <nav class="nav navbar">
      <div class="logo"> 
      <%= link_to image_tag("twixterlogo.png", class: "icon"), root_path %></div>
        </nav>
        <% if user_signed_in? -%>
						<ul class="nav navbar-nav navbar-center">
							<l1><h1> Welcome to Twixter, <%= current_user.name %></h1></l1>
						</ul>
            <nav class="blog-nav">
              <a class="blog-nav-item"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: "btn btn-large btn-primary" %>
              </a>
            <a class="blog-nav-item"><%= link_to 'Twixt!', new_twixt_path, class: "btn btn-large btn-primary" %>
              </a>
						<%unless current_user.avatar.blank?%>
						<a class="blog-nav-item"><%=link_to image_tag(current_user.avatar.thumb.url), edit_registration_path(:user)  %>
              </a>
						<% end %>
       
        <% else -%>
            <nav class="blog-nav">
            <a class="blog-nav-item"><%= link_to 'Join us', new_user_registration_path, class: "btn btn-large btn-primary" %></a>
             <a class="blog-nav-item"><%= link_to 'Sign in', new_user_session_path, class: "btn btn-large btn-primary" %></a>
             <a class="blog-nav-item"><%= link_to 'Sign in with Google', user_omniauth_authorize_path(:google_oauth2), class: "btn btn-large btn-primary" %></a>
        <% end -%>
            </nav>
          </nav>
        </div>
      </nav>
    </div>
  </div>


<div id="main_content" class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
</div>

<div class="container">
  <%= yield %>
</div>
 

</body>
</html>

app/views/twixts/_form.html.erb
<%= form_for(@twixt) do |f| %>
    <% if @twixt.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@twixt.errors.count, "error") %> prohibited this link from being saved:</h2>

          <ul>
            <% @twixt.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :content %><br>
      <%= f.text_area :content, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.submit class: "btn btn-large btn-primary"  %>
    </div>
    
<% end %>   

app/views/twixts/index.html.erb
<div class="page-container">
  <span><%= link_to 'User List', users_path, class: "btn btn-small btn-primary" %> 
  </span>
  <% unless current_user.blank? %>
  <span><%= link_to 'Your Timeline', timeline_path(current_user.id), class: "btn btn-small btn-primary" %>
  </span>
  <% end %>
	<span><%= form_tag("/search", method: "get") do %>
            <%= label_tag(:word, "Search for:") %>
				<%= text_field_tag(:word) %>
				<%= submit_tag("Search") %>
        <% end %></span>
</div>
<div class="content">
<% @twixts.each do |twixt| %>
    <div class="twixt">
    <% if twixt.user.avatar? %>
      <img class="avatar" src="<%= twixt.user.avatar.medium_avatar %>"> 
      <% else %>
      <%= image_tag "default_avatar.png", size: "50x50", class: "avatar" %>
      <% end %>
      <h2><%=  twixt.content %></h2>
      <p class="author">Submitted <%= time_ago_in_words(twixt.created_at) %> ago by <%= twixt.user.name %></p>
      <br>
			<%= link_to 'User Profile', user_path(twixt.user.id), class: "btn btn-small btn-primary" %>
      <%= link_to 'Show Twixt', twixt_path(twixt), class: "btn btn-small btn-primary" %>
      <br>
    </div>
<% end %>
</div>
<div class="link row clearfix">
    <%= paginate @twixts %>
  </div>
</div>

app/views/twixts/new.html.erb
<h1>Twixt away, <%= current_user.name %>!</h1>

<%= render 'form' %>

<%= link_to 'Back', twixts_path, class: "btn btn-large btn-primary" %>

app/views/twixts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="content">
  <h2><%= @twixt.content %></h2>
    <br>
    <small class="author">Submitted <%= time_ago_in_words(@twixt.created_at) %> 
      ago by <%= @twixt.user.name %></small>
      <p><%= link_to 'User Profile', user_path(@twixt.user.id), 
                      class: "btn btn-small btn-primary"%>
      </p>
    </div>
 

<h3> Comments: </h3>
<% @twixt.comments.each do |comment| %>
<div class="content">
  <h4><%= comment.author %></h4>
  <h4><%= comment.title %></h4>
  <h4><%= comment.body %></h4>
 <h5><%= comment.user %></h5>
  
    <h6><%= link_to 'Delete', twixt_comment_path(@twixt, comment), method: :delete, data: { confirm: 'Are you sure?' }
		%></h6>
  
<% end %>
</div>
    
    <div class="container">
      <%= form_for([@twixt, @comment]) do |f| %>
      <%= f.hidden_field :author, :value => current_user.id %>
      <%= f.label :body %>
      <%= f.text_area :body %><br>
      <%= f.submit class: "btn btn-small btn-primary" %>
      <%= link_to 'Back', twixts_path, class: "btn btn-small btn-primary" %>
      <% end %>
    </div>

    

app/views/users/index.html.erb
<div class= "users-list">
<% provide(:title, 'Users') %>
<h1>All the Twixters, Twixting:</h1>
</div>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%=  %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/search.html.erb
<h3>Twixts that match your search term:</h3>
<% @twixts.each do |twixt| %>

		<div class="link-row-clearfix">
			<h2>
				<%=twixt.content %><br>
				<small class="author"> Submitted <%=time_ago_in_words(twixt.created_at)%> ago by <%=twixt.user.name %></small>
			</h2>
			<p><%= link_to 'User Profile', user_path(twixt.user.id), class: "btn btn-small btn-primary"
			%></p>
		</div>
<% end %>

app/views/users/show.html.erb
<div class="user-profile-header">
  <h1><%=@user.name  %>'s Profile Page</h1>
  <%if @user.avatar.present? %>
    <p><%= image_tag(@user.avatar.url) %></p>
  <% end  %>
</div>

<div class="user-follow">
  <% if @user.followed_by?(current_user)  %>
  <%= link_to 'Unfollow this user', unfollow_user_path(@user.id), class: "btn btn-small btn-danger", notice: "You are
  no longer following this user"%>
  <%else  %>
  <%= link_to 'Follow this user', follow_user_path(@user.id), class: "btn btn-small btn-primary", notice: "You are now
  following this user" %>
  <%end  %>
</div>
  <div><h3 class="follow-header"> Following: <%= @user.follow_count %></h3>
       <h3 class="follow-header"> Followers: <%= @user.followers_count %></h3>
       <h3 class="follow-header"> Twixts: (<%=@twixts.count%>)</h3>
  <div>
  <div class="view">
    <% @twixts.each do |twixt|  %>
     <h2>
      <%= twixt.content %><br>
      <small class="author">Submitted <%= time_ago_in_words(twixt.created_at) %> ago</small>
    </h2>
  </div>
  <%end %>

app/views/users/timeline.html.erb
<div class="follows-top">
  <h3>You are following:</h3>
    <% current_user.all_following.each do |follow|%>
  <h4><%= link_to follow.name, follow %> </h4>
<% end %>
</div>
  <h3>Twixts in your timeline:</h3>
    <% @twixts.each do |twixt| %>

<div class="link-row-clearfix">
  <h2>
    <%=twixt.content %><br>
    <small class="author"> Submitted <%=time_ago_in_words(twixt.created_at)%> 
      ago by <%=twixt.user.name %></small>
  </h2>
</div>
<% end %>


<div class="link row clearfix">
 <%= link_to 'Back', twixts_path, class: "btn btn-small btn-primary" %>
  <%= paginate @twixts %>
</div> 